/**
 * API auth codes from backend (keep in sync with server).
 */
export const AUTH_CODES = {
  SUCCESS_AUTH_REGISTERED: "SUCCESS_AUTH_REGISTERED",
  SUCCESS_AUTH_LOGGED_IN: "SUCCESS_AUTH_LOGGED_IN",
  SUCCESS_AUTH_LOGGED_OUT: "SUCCESS_AUTH_LOGGED_OUT",
  SUCCESS_AUTH_TOKEN_REFRESHED: "SUCCESS_AUTH_TOKEN_REFRESHED",
  SUCCESS_AUTH_PROFILE_RETRIEVED: "SUCCESS_AUTH_PROFILE_RETRIEVED",
  SUCCESS_AUTH_PROFILE_UPDATED: "SUCCESS_AUTH_PROFILE_UPDATED",

  ERROR_AUTH_INVALID_CREDENTIALS: "ERROR_AUTH_INVALID_CREDENTIALS",
  ERROR_AUTH_EMAIL_EXISTS: "ERROR_AUTH_EMAIL_EXISTS",
  ERROR_AUTH_TOKEN_EXPIRED: "ERROR_AUTH_TOKEN_EXPIRED",
  ERROR_AUTH_TOKEN_INVALID: "ERROR_AUTH_TOKEN_INVALID",
  ERROR_AUTH_TOKEN_MISSING: "ERROR_AUTH_TOKEN_MISSING",
  ERROR_AUTH_UNAUTHORIZED: "ERROR_AUTH_UNAUTHORIZED",
  ERROR_AUTH_REFRESH_TOKEN_INVALID: "ERROR_AUTH_REFRESH_TOKEN_INVALID",
  ERROR_AUTH_PASSWORD_WEAK: "ERROR_AUTH_PASSWORD_WEAK",
  ERROR_AUTH_PHONE_EXISTS: "ERROR_AUTH_PHONE_EXISTS",
  ERROR_AUTH_USER_NOT_FOUND: "ERROR_AUTH_USER_NOT_FOUND",
  ERROR_AUTH_RESET_TOKEN_INVALID: "ERROR_AUTH_RESET_TOKEN_INVALID",
} as const;

export type AuthApiCode = (typeof AUTH_CODES)[keyof typeof AUTH_CODES];
